[versions]
agp = "8.3.1"
ksp = "1.9.23-1.0.19"
kotlin = "1.9.10"
kotlin_compose_version = "1.5.2"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.8.2"
constraintlayout = "2.1.4"
kotlinCoroutines = "1.8.0"
lifecycle = "2.2.0"
concurrentfuturesktx = "1.1.0"
fragmentKtx = "1.3.6"
navigationFragmentKtx = "2.3.5"
splashscreen = "1.0.0"
recyclerview = "1.3.0"
windowVersion = "1.2.0"
multidex = "2.0.1"
room = "2.6.1"
paging = "3.2.1"
retrofit = "2.9.0"
okhttp3 = "4.9.0"
loggingLnterceptor = "4.9.0"
gson = "2.8.8"
retrofitUrlManager = "1.4.0"
glide = "5.0.0-rc01"
permissionx = "1.7.1"
xxpermission = "18.62"
debugDb = "1.0.6"
xpopup = "2.9.19"
longan = "1.1.1"
utilcodex = "1.31.1"
baseRecyclerViewAdapterHelper = "4.1.2"
camerax = "1.3.1"
vasdolly = "3.0.6"
immersionbar = "3.2.2"
scwang90Refresh = "2.0.5"
compressor = "3.0.1"
imagezoom = "1.0.4"
smartCropper = "v2.1.3"
bugly = "4.1.9.3"
umengCommon = "9.6.7'"
umengAsms = "1.8.0'"
mengUyumao = "1.1.2"
itextpdf = "8.0.3"
pdfViewer = "2.8.2"
unpeekLivedata = "7.8.0"
agentWeb = "v5.0.6-androidx"
datastoreKtx = "1.0.0"
liulishuo = "1.7.7"
theRouter = "1.3.0-rc4"
androidxWebkit = "1.0.0"
composeBom = "2023.03.00"
activity-compose = "1.7.0"
lifecycleViewmodelCompose = "2.5.1"
opencv = "4.9.0"
lucksiege = "v3.11.2"
gmsversion = "23.2.0"
[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "windowVersion" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "androidxWebkit" }

google-gms = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "gmsversion" }


core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragmentKtx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }


#lifecyclelibs
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }

lifecycle-common-java = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
futures-ktx = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "concurrentfuturesktx" }

#kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }

#room
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

#paging
paging-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }

#net
squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
squareup-retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
squareup-retrofit2-adapter-rxjava3 = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit" }

okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "loggingLnterceptor" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

retrofit-url-manager = { group = "me.jessyan", name = "retrofit-url-manager", version.ref = "retrofitUrlManager" }

#glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }

#permission
permixxionx = { group = "com.guolindev.permissionx", name = "permissionx", version.ref = "permissionx" }
xxpermixxion = { group = "com.github.getActivity", name = "XXPermissions", version.ref = "xxpermission" }

#camerax
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
camera-extensions = { group = "androidx.camera", name = "camera-extensions", version.ref = "camerax" }

#compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }

compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
compose-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-runtime-rxjava2 = { group = "androidx.compose.runtime", name = "runtime-rxjava2" }


#vasdolly
vasdolly-plugin = { group = "com.tencent.vasdolly", name = "plugin", version.ref = "vasdolly" }
vasdolly-helper = { group = "com.tencent.vasdolly", name = "helper", version.ref = "vasdolly" }

#Immersionbar
immersionbar = { group = "com.geyifeng.immersionbar", name = "immersionbar", version.ref = "immersionbar" }
immersionbar-ktx = { group = "com.geyifeng.immersionbar", name = "immersionbar-ktx", version.ref = "immersionbar" }

#RefreshLayout
scwang90-refresh = { group = "io.github.scwang90", name = "refresh-layout-kernel", version.ref = "scwang90Refresh" }
scwang90-refresh-header-classics = { group = "io.github.scwang90", name = "refresh-header-classics", version.ref = "scwang90Refresh" }
scwang90-refresh-header-radar = { group = "io.github.scwang90", name = "refresh-header-radar", version.ref = "scwang90Refresh" }
scwang90-refresh-header-falsify = { group = "io.github.scwang90", name = "refresh-header-falsify", version.ref = "scwang90Refresh" }
scwang90-refresh-header-material = { group = "io.github.scwang90", name = "refresh-header-material", version.ref = "scwang90Refresh" }
scwang90-refresh-header-two-level = { group = "io.github.scwang90", name = "refresh-header-two-level", version.ref = "scwang90Refresh" }
scwang90-refresh-tooter-ball = { group = "io.github.scwang90", name = "refresh-footer-ball", version.ref = "scwang90Refresh" }
scwang90-refresh-tooter-classics = { group = "io.github.scwang90", name = "refresh-footer-classics", version.ref = "scwang90Refresh" }

#library
debug-db = { group = "com.amitshekhar.android", name = "debug-db", version.ref = "debugDb" }
xpopup = { group = "com.github.li-xiaojun", name = "XPopup", version.ref = "xpopup" }
longan = { group = "com.github.DylanCaiCoding.Longan", name = "longan", version.ref = "longan" }
longan-design = { group = "com.github.DylanCaiCoding.Longan", name = "longan-design", version.ref = "longan" }
utilcodex = { group = "com.blankj", name = "utilcodex", version.ref = "utilcodex" }
baseRecyclerViewAdapterHelper = { group = "io.github.cymchad", name = "BaseRecyclerViewAdapterHelper4", version.ref = "baseRecyclerViewAdapterHelper" }
compressor = { group = "id.zelory", name = "compressor", version.ref = "compressor" }
imagezoom = { group = "it.sephiroth.android.library.imagezoom", name = "library", version.ref = "imagezoom" }
smartCropper = { group = "com.github.pqpo", name = "SmartCropper", version.ref = "smartCropper" }
bugly = { group = "com.tencent.bugly", name = "crashreport", version.ref = "bugly" }

umeng-common = { group = "com.umeng.umsdk", name = "common", version.ref = "umengCommon" }
umeng-uyumao = { group = "com.umeng.umsdk", name = "uyumao", version.ref = "mengUyumao" }
umeng-asms = { group = "com.umeng.umsdk", name = "asms", version.ref = "umengAsms" }

itext = { group = "com.itextpdf", name = "itext7-core", version.ref = "itextpdf" }
android-pdf-viewer = { group = "com.github.barteksc", name = "android-pdf-viewer", version.ref = "pdfViewer" }
unpeek-livedata = { group = "com.kunminx.arch", name = "unpeek-livedata", version.ref = "unpeekLivedata" }
agaentweb = { group = "com.github.Justson.AgentWeb", name = "agentweb-core", version.ref = "agentWeb" }
datastore-ktx = { group = "com.github.DylanCaiCoding.DataStoreKTX", name = "datastore-ktx", version.ref = "datastoreKtx" }
liulishuo = { group = "com.liulishuo.filedownloader", name = "library", version.ref = "liulishuo" }

lucksiege-pictureselector = { group = "io.github.lucksiege", name = "pictureselector", version.ref = "lucksiege" }
lucksiege-compress = { group = "io.github.lucksiege", name = "compress", version.ref = "lucksiege" }
lucksiege-ucrop = { group = "io.github.lucksiege", name = "ucrop", version.ref = "lucksiege" }
lucksiege-camerax = { group = "io.github.lucksiege", name = "camerax", version.ref = "lucksiege" }

therouter = { group = "cn.therouter", name = "router", version.ref = "theRouter" }
therouter-apt = { group = "cn.therouter", name = "apt", version.ref = "theRouter" }

opencv = { group = "org.opencv", name = "opencv", version.ref = "opencv" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
therouter = { id = "cn.therouter.agp8", version.ref = "theRouter" }
